### ISSUE TITLE
Property names and values of TDM-a and TDM-b

### ISSUE THREAD

**Issue by llemeurfr** [w3c/tdm-reservation-protocol#16]
It is now time for a "bike-shedding round": we have worked so far with two properties:

- TDM-a is a flag with three values
   0 = tdm rights are not reserved
   1 = tdm rights are reserved 
   2 = tdm rights are reserved and a TDM policy is available
- TDM-b is a URL, set only if mining is conditional, with points to a policy. The policy offers details on how to contact the rightsholder and give clues on what to expect. 

What would be your preferred names and values for these properties?

**Comment by llemeurfr** [comment]
My very personal proposal is: 

- "tdm-signal" with values 0,1 or 2
- "tdm-policy" as a URL. 

Note that [MDN on HTTP Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) specifies that we dont need to add an  "X-" prefix anymore. We should still register "TDM-Signal" and "TDM-Policy" to IANA (the would appear in https://www.iana.org/assignments/message-headers).

ps: I hesitated with "tdm-flag" but flag is usually a boolean.

**Comment by Jean-Baptiste-de-Vathaire** [comment]
for tdm-a, an option could be "tdm-declaration" since it is a declaration of right's reservation.

**Comment by Jean-Baptiste-de-Vathaire** [comment]
Another option for the tdm-a could be "tdm-reservation".

**Comment by RobinLeMaroisSeraphin** [comment]
I agree with (i) tdm-declaration because it is self-explanatory and (ii) tdm-policy for tdm-b

**Comment by claudiotubertini** [comment]
I'm happy with tdm-signal and tdm-policy.

**Comment by giuliamarangoni** [comment]
Hi All,
here's my proposals: 

TDM_RightsReservation_Type

TDM_RightsReservation_Policy

The idea is to use the term RightsReservation for consistency with the art.4 terminology, The _Type suffix is meant to introduce a list of options (0-1-2), where 0 stands for: "no TDM rights reservation" 1 for " TDM rights are reserved" 2 for "TDM rights are reserved and license information are available" ( i think it is preferable to say "and" instead of "but", and say that information about licenses are available, as ORDL policy are not licenses but information on license)

**Comment by llemeurfr** [comment]
@giuliamarangoni, a caveat with your proposal is that the more characters there are, the more chances that a developer will mistype one character. And a bad character means no detection by TDM Agents. Plus the underscore is a character people tend to mistype.

**Comment by giuliamarangoni** [comment]
I see. Maybe we could cut "rights" to shorten it? on the underscore: no strong preference on this, also other separators are ok!

**Comment by llemeurfr** [comment]
We've used the acronym `tdmrep` from the start of this project. @giuliamarangoni would it be ok instead of `tdm-rights`?

**Comment by llemeurfr** [comment]
During the community call, the following terms have been chosen:

tdm-reservation
tdm-policy
