### ISSUE TITLE
Should we remove the value 2 of tdm-reservation? 

### ISSUE THREAD

**Issue by llemeurfr** [w3c/tdm-reservation-protocol#23]
This was proposed during the call of the 27th June during a discussion about #20. 

tdm-reservation = 2 indicates that "tdm rights are reserved and a policy is available". If we consider that a missing (or unreachable) tdm-profile is not a protocol error, then it would be simpler to suppress this value 2 and keep only value 1 with an **optional** tdm-profile. 

In such a case, when the policy is not set or unreachable, the TDM Actor must simply not process the content during this round of scraping.

**Comment by llemeurfr** [comment]
The same issue applies to machine-readable TDM Policies that could be un-parsable as ODRL 2 files. Is it a protocol error and therefore is `tdm-reservation` considered `unset`? By removing value 2 and keeping value 1 for `tdm-reservation`, such error would end up considering that the content provider states that "TDM rights are reserved" without further "conditions for access".

**Comment by claudiotubertini** [comment]
With the actual structure the separation of concern is clear:
1. tdm-reservation = 0 means NO
2. tdm-reservation = 1 means YES and TDM Actors do not have to worry for anything else.
3. tdm-reservation = 2 means YES and there is also a Policy.  

If we eliminate the last option we simply put together two different concerns creating a bit of a mess. With tdm-reservation as 1, is there a policy or there is no policy? If TDM Actors, for whatever reason, do not find a policy, they have to ask themselves: what it means? What kind of reservation is this one? Is there somewhere a policy, the reservation is unset or simply I've done a mistake and I can't find the policy?
I think it would be unwise removing tdm-reservation = 2. Or at least if we remove the value 2 we have to consider compulsory adding a policy when the value is 1, and that I think it is not what we want.

**Comment by llemeurfr** [comment]
Well, I can't totally agree with @claudiotubertini. Because `tdm-reservation` (boolean) and 'tdm-policy` (url) are separate properties, 

- a TDM Agent which sees `tdm-reservation` = 1 and NO 'tdm-policy` would assume that there is NO way to get rights to use the content and
- a TDM Agent which sees `tdm-reservation` = 1 and A 'tdm-policy` would assume that there is A way to get rights to use the content.

**Comment by llemeurfr** [comment]
During the Sept 6th meeting, the group decided to remove this value 2 from the spec and reword the spec accordingly. This means that a certain kind of protocol errors will not be possible anymore, which simplifies processing by TDM Agents.
