### ISSUE TITLE
Clarifications on Vocabulary

### ISSUE THREAD

**Issue by lrosenthol** [w3c/tdm-reservation-protocol#3]
I'd like to offer two changes to the currently specified vocabulary

>TDM Agent: software crawling web content for TDM purposes.

I would change the word `crawling` to `accessing`, since the method of access doesn't change the TDM scenario.

>Web resource: identifiable thing available on the Web, e.g. HTML formatted text, an image, audio or video file. Web resources are located using URLs.

I would remove everything `, e.g. HTML formatted text, an image, audio or video file` and replace it with `(Wikipedia)` as you do for other definitions, since there is a perfectly acceptable page there (https://en.wikipedia.org/wiki/Web_resource) that defines it.

**Comment by llemeurfr** [comment]
I agree with your proposals. We'll discuss them during the next call.

**Comment by llemeurfr** [comment]
Fixed by #8.
