### ISSUE TITLE
Incompatible datatypes with VCard

### ISSUE THREAD

**Issue by RinkeHoekstra** [w3c/tdm-reservation-protocol#38]
The VCard ontology specifies `vcard:hasEmail` and `vcard:hasTelephone` as object properties (i.e. they have a URI as value). This specification dictates the use of strings, which is not compatible with VCard, unless the JSON-LD context for this spec turns the values into URIs.

https://github.com/w3c/tdm-reservation-protocol/blob/a1e0c76ac2cc9da602a8f916951c70a4c33b6b18/spec/index.html#L474-L477

**Comment by llemeurfr** [comment]
I find in https://www.w3.org/TR/vcard-rdf/, section 3 Examples

```json
{
  "@context": "http://www.w3.org/2006/vcard/ns",
  "@id": "http://example.com/me/corky",
  "@type": "Individual",
  "fn": "Corky Crystal",
  "nickname": "Corks",
  "hasEmail": "mailto:corky@example.com",
  "hasAddress": {
    "@type": "Home",
    "country-name": "Australia",
    "locality": "WonderCity",
    "postal-code": "5555",
    "street-address": "111 Lake Drive"
  },
  "hasTelephone": {
    "@type": [ "Home", "Voice" ],
    "hasValue": "tel:+61755555555"
  }
}
```

We will rephrase the definition, you are right. The type of an email or telephone may be useful. 
To good thing is that the sample is still ok, as "mailto:xxx" is a URI, same for "tel:xxx".
