### ISSUE TITLE
Clarifications on Requirements

### ISSUE THREAD

**Issue by lrosenthol** [w3c/tdm-reservation-protocol#4]
I would make the following changes to the Requirements.

>Rely on tools and formats widely supported by web crawlers.

Since, as I commented in #3 , TDM applies to cases **other than crawlers**, while this is important it should be a secondary requirement and not a primary one.

>Be easy to implement, with no economic or technical barriers.

Easy is a problematic word, I would rewrite this sentence as:
"Able to be implemented without any economic or technical barriers"

>Specify how a rightsholder can declare TDM rights on each individual Web resource he controls, when such Web resources are present in a Web page.

Most web resources are not `present` in a Web page, they are, instead, *referenced* by a Web page. I would therefore change `present in` to `referenced by`.

>Specify how the rightsholder can indicate whether a licence for TDM rights is available (in case TDM rights are reserved).

I believe that this should also include similar language to the above about "individual resources..."

>Specify how a TDM actor can apply for a TDM license.

Since a TDM Actor is a machine process, should we say anything here about a "machine processable application"??

>Specify a machine-readable format for TDM licenses.

Given the scope of supporting all Web Resources, I wonder if we should change this to be "**at least** one"?

>Specify how a rightsholder can indicate that TDM rights are reserved on random Web resources he controls (e.g. images and video files which may be found by crawlers outside of Web pages).

Since the EU Directive says *NOTHING* about web crawling (as noted also in #3 ), this needs to be a primary requirement in order to deliver a solution that actually meets the needs of the EU Directive.

**Comment by llemeurfr** [comment]
The major question we will have to decide on is about the scope of the work: is it only about web pages and resources referenced there (in which case a solution based on a json-ld manifest embedded in the web page works) or is it about any web resource accessed on the web (in which case embedding data inside the resource does not work and a solution based on http headers is fine)?

We'll share info about existing solutions, more or less adaptable to our use case, to make it clear.

**Comment by lrosenthol** [comment]
> in which case embedding data inside the resource does not work
>
Why not?   There are standards in place today for asset-embedded metadata, eg. XMP (ISO 16684), for exactly this purpose.

**Comment by llemeurfr** [comment]
Fixed by #8.
