### ISSUE TITLE
Potential Requirement: move TDM rights with the associated content

### ISSUE THREAD

**Issue by llemeurfr** [w3c/tdm-reservation-protocol#7]
Should we add the requirement to be able move a resource from one server to another, and have automatically all TDM rights still apply?

If this requirement is added, it will have important consequences on the technical solution, as TDM metadata will have to be embedded in each resource, whatever its format is.

**Comment by lrosenthol** [comment]
I will say that I consider this to be an optional requirement - in that it should be available to publishers that require it, but that it not be the only option.

**Comment by llemeurfr** [comment]
Let's discuss the use cases which would make us decide this is a valid additional requirement. 

I'm not certain that the transfer from one Web server to another is a definitive use case for embedding TDM info as content metadata, because solutions based on http headers or on a central file can be made easily configurable to cover this use case.

And when a publication is transferred from a producer to a distributor (retailer/library...), I suspect that ONIX metadata would be the preferred channel to convey such information.

**Comment by lrosenthol** [comment]
> because solutions based on http headers or on a central file can be made easily configurable to cover this use case.

I would love to see a proposal for that, because I can't think of any model that would address that...in the context that the file is moved w/o explicit action by the current storage system.

>And when a publication is transferred from a producer to a distributor (retailer/library...), I suspect that ONIX metadata would be the preferred channel to convey such information.

ONIX is a metadata *schema* - it is not a metadata model nor does it say anything about serialization of that information into various asset formats.

**Comment by llemeurfr** [comment]
The requirement has not be retained by the CG.
