### ISSUE TITLE
TDM Reservation Protocol vs Trust

### ISSUE THREAD

**Issue by llemeurfr** [w3c/tdm-reservation-protocol#9]
Let's imagine that a TDM Actor checks that TDM is allowed on some content, processes such content accordingly, and is then attacked by a publisher who has in fact modified the TDM info associated with the content at a later stage. 

Is there a way to protect TDM Actors against such problem, i.e. can we embed Trust in the technical solution? 

This is not an issue for web crawlers using robots.txt, which is transient (the no-index can be added or removed at any given time, this is only an indication for the crawler about how it can optimize its indexing). 
But it could be an issue with TDM rights. 

Embedding metadata in the content could be seen as a proper solution for that, but trust would only be real if the whole asset (content + TDM info) was protected against tempering, i.e. was signed by the publisher. I doubt this can happen in real life. 

If would be interesting to study past and existing initiatives in the light.

**Comment by lrosenthol** [comment]
I don't see how "trust" resolves your use case.  Who is trusting whom?  What are they trusting?

**Comment by llemeurfr** [comment]
See the new [Charter of the Linked Data Signature WG](https://w3c.github.io/lds-wg-charter/). If created, the mission of this group would be to create a way to sign things like an ODRL Policy. 

We can therefore imagine a dated ODRL Policy which contains a copy of the choice made by a publisher (tdm-a and tdm-b) and is signed. With that, no rightsholder can assert that a policy grabbed at a certain time did not exist.

**Comment by llemeurfr** [comment]
Closed as outside of the charter of the CG.
